server:
  port: 9898
spring:
  application:
    name: es
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.65.40:9300
      properties:
        transport.tcp.connect_timeout : 60s


