#生产配置
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
logging:
  config: classpath:logback-spring.xml
  file: fss
  path: /var/log/fss/1.0
---
fileTransfer:
  root: /usr/local/fss/1.0/file
  temp: /usr/local/fss/1.0/temp