spring:
  profiles:
    active: prod
  application:
    name: fss
  datasource:
    continue-on-error: true
    url: jdbc:mysql://127.0.0.1:3306/fss
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 10
    maxActive: 25
    max-idle: 20
    min-idel: 10
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    show-sql: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 10Mb
      max-request-size: 50Mb
  thymeleaf:
    prefix : classpath:/templates/
    encoding : UTF-8
    cache : false
    mode : HTML5
---
mybatis:
  config-location: classpath:mybatis-config.xml
pagehelper:
  auto-dialect: true
  close-conn: true
#  level:
#    com.glodon.coca.services.iot.mapper.TowerDataMapper : DEBUG
#---
#mybatis:
#  config-location: classpath:mybatis-config.xml
#pagehelper:
#  auto-dialect: true
#  close-conn: true
#---
#spring:
#  redis:
#    database: 0
#    host: 127.0.0.1
#    password: 123456
#    port: 6379
#    pool:
#      min-idle: 0
#      max-idle: 8
#      max-active: 8
#      max-wait: -1
#---
#spring:
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: wangkan
#    password: wangkan
#    publisher-confirms: true

